name: Amelia McNamara
description: Amelia McNamara, assistant professor of statistics in the Department of Computer & Information Sciences at the University of St Thomas 
highlighter: rouge
timezone: America/Chicago
markdown: kramdown
destination: docs
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
baseurl: "https://www.amelia.mn"
permalink: blog/:categories/:year/:month/:day/:title.html
excerpt_separator: <!--more-->