name: Amelia McNamara
description: Personal website of Amelia McNamara, statistical and data sciences professor at Smith College.
markdown: redcarpet
highlighter: rouge
baseurl: "http://www.science.smith.edu/~amcnamara"
permalink: blog/:categories/:year/:month/:day/:title.html
excerpt_separator: <!--more-->