project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "*.rmd"
    - "!SpeakingR/"
    - "!presentations/noRth2020/"
    - "!presentations/syntax/"
  resources:
    - "SpeakingR/"
    - "presentations/noRth2020/"
    - "presentations/syntax/"
    - "presentations/user2022_files"
    - "presentations/BestPractices_files"
    - "mytwitterarchive/"

website:
  title: "Amelia McNamara"
  site-url: https://www.amelia.mn
  description: "Amelia McNamara, Associate Professor of data science in the Department of Computer & Information Sciences at the University of St Thomas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Teaching"
        menu:
          - STAT220labs.qmd
          - text: "STAT 336: Data Communication and Visualization"
            href: https://ameliamn.github.io/STAT336
          - pastcourses.qmd
          - href: Syntax-cheatsheet.pdf
            text: R Syntax Comparison Cheatsheet
          - wikipedia.qmd
      - text: "Research"
        menu:
          - writing.qmd
          - presentations.qmd
      - press.qmd
      - text: Blog
        href: blog.qmd
    right:
      - icon: envelope
        href: mailto:amelia.mcnamara@stthomas.edu
      - icon: mastodon
        href: https://vis.social/@amelia
      - icon: youtube
        href: https://www.youtube.com/ameliamcnamara
      - icon: linkedin
        href: http://www.linkedin.com/in/AmeliaMcNamara
      - icon: github
        href: https://github.com/AmeliaMN/
  page-footer: 
    left:
      - text: "Copyright © 2024 Amelia McNamara. All Rights Reserved."
      

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
execute: 
  freeze: auto

editor: visual

