---
title: "Writing"
---


Here are some links to recent writing I've done, both in peer-reviewed publications and on blogs.

### Publications 

- McNamara, A. **Teaching modeling in introductory statistics: A comparison of formula and tidyverse syntaxes.** *Under review.* [pre-print](https://arxiv.org/abs/2201.12960).  
- Cetinkaya-Rundel, M., Hardin, J., Baumer, B., McNamara, A., Horton, N.J., Rundel, C. **An educator's perspective of the tidyverse** *[Technology Innovations in Statistics Education](https://escholarship.org/uc/item/7kk4d922)*, Vol. 14, Issue 1.  ([pre-print](https://arxiv.org/abs/2108.03510)).   
- McNamara, A. **Community engagement and subgroup meta-knowledge: Some factors in the soul of a community.** *[Computational Statistics](https://link.springer.com/article/10.1007/s00180-019-00879-x)*, Vol. 34, Issue 4 ([pre-print](https://github.com/COSTDataExpo2013/AmeliaMN/blob/master/PaperFinalDraft.pdf) and [code](https://github.com/COSTDataExpo2013/AmeliaMN)) 
- McNamara, A. **Key attributes of a modern statistical computing tool**, *https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1482784">The American Statistician</a>*, Vol. 73, Issue 4. ([pre-print](https://arxiv.org/abs/1610.00985), [blog post](http://www.amelia.mn/blog/papers/2019/11/21/Key-Attributes.html)) 
<!-- - McNamara, A. **On the state of computing in statistics education: Tools for learning and for doing.** (submitted, https://arxiv.org/abs/1610.00984">pre-print</a>)  -->
- McNamara, A., and Horton, N. J. **Wrangling categorical data in R**, *[The American Statistician](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1356375)*, Vol. 72, Issue 1 (pre-print in [PeerJ Collection](https://peerj.com/preprints/3163/)) 
- McNamara, A., Horton, N.J., Baumer, B. **Greater data science at baccaleureate institutions**, *[Journal of Computational and Graphical Statistics](https://www.tandfonline.com/doi/abs/10.1080/10618600.2017.1386568)*, Vol. 26, No 4.
- McNamara, A. **Considering the gap between learning and doing statistics.** *International Handbook of Research in Statistics Education.* In chapter 15, The Future of Research in Statistics Education. (2015) 
- McNamara, A. **Barriers and opportunities for nurturing statistical thinking before college.** *CHANCE [Vol. 28, Issue 4](http://amstat.tandfonline.com/doi/full/10.1080/09332480.2015.1120126]*. (2015) 
- McNamara, A. and Hansen, M. **Teaching Data Science to Teenagers.** *[Proceedings of the 9th International Conference on Teaching Statistics](http://icots.info/9/proceedings/pdfs/ICOTS9_9C2_MCNAMARA.pdf)* (2014). 
- McNamara, A. **Dynamic Documents with R and knitr (book review).** *Journal of Statistical
Software*, [Vol. 56, Book Review 2](http://www.jstatsoft.org/v56/b02). (2014). 
- Catll&aacute;, A.J., McNamara, A. and Topaz, C. M. **Instabilities and Patterns in Coupled Reaction-Diffusion Layers.** *Physical Review E*, Vol. 85, Issue 2. ([pre-print](http://arxiv.org/abs/1201.4417)). (2012). 

### Blog posts

- McNamara, A. **[Data visualisation by hand: drawing data for your next story](https://datajournalism.com/read/longreads/data-visualisation-by-hand)**. DataJournalism.com, March 24 2021. 
- McNamara, A. [Counting commits and peer code review](https://teachdatascience.com/countingcommits/). Teach Data Science, July 28, 2019. 
