\documentclass[10pt]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

\usepackage{amsmath,amssymb,amsthm}
\usepackage{fancyhdr,url,hyperref}
\usepackage{graphicx,xspace}
\usepackage{subfigure}
\usepackage{tikz}
\usetikzlibrary{arrows,decorations.pathmorphing,backgrounds,positioning,fit,through}
\usepackage{soul}

\oddsidemargin 0in  %0.5in
\topmargin     0in
\leftmargin    0in
\rightmargin   0in
\textheight    9in
\textwidth     6in %6in
%\headheight    0in
%\headsep       0in
%\footskip      0.5in

\newtheorem{thm}{Theorem}
\newtheorem{cor}[thm]{Corollary}
\newtheorem{obs}{Observation}
\newtheorem{lemma}{Lemma}
\newtheorem{claim}{Claim}
\newtheorem{definition}{Definition}
\newtheorem{question}{Question}
\newtheorem{answer}{Answer}
\newtheorem{problem}{Problem}
\newtheorem{solution}{Solution}
\newtheorem{conjecture}{Conjecture}

\pagestyle{fancy}

\lhead{\textsc{Prof. McNamara}}
\chead{\textsc{SDS/MTH 220: Lecture notes}}
\lfoot{}
\cfoot{}
%\cfoot{\thepage}
\rfoot{}
\renewcommand{\headrulewidth}{0.2pt}
\renewcommand{\footrulewidth}{0.0pt}

\newcommand{\ans}{\vspace{0.25in}}
\newcommand{\R}{{\sf R}\xspace}
\newcommand{\cmd}[1]{\texttt{#1}}

\rhead{\textsc{October 16, 2017}}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\paragraph{Agenda}
\begin{enumerate}
  \itemsep0em
  \item Applying the Normal Model
  \item Confidence Intervals
\end{enumerate}

\paragraph{Applying the Normal Model}

Recall the baseball example from last time. 

\begin{knitrout}\footnotesize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}


{\ttfamily\noindent\color{warningcolor}{\#\# Warning: package 'dplyr' was built under R version 3.3.2}}

{\ttfamily\noindent\color{warningcolor}{\#\# Warning: package 'bindrcpp' was built under R version 3.3.2}}\begin{verbatim}
##    playerID yearID      BAvg
## 1 willite01   1941 0.4057018
## 2 brettge01   1980 0.3897550
## # A tibble: 2 x 4
##   yearID     N mean_BAvg    sd_BAvg
##    <int> <int>     <dbl>      <dbl>
## 1   1941    98 0.2806367 0.03279026
## 2   1980   148 0.2788247 0.02757441
\end{verbatim}
\end{kframe}
\end{knitrout}

George Brett, who hit .390 in 1980, won the AL MVP. The player who finished second in the balloting, \href{https://www.google.com/search?q=reggie+jackson+baseball}{Reggie Jackson}, hit .300 (with 41 home runs). Let's examine Jackson's batting average in the context of his peers. What we need is a way to understand the \emph{distribution} of batting average in the AL in 1980. We have three different ways to do this:

\begin{enumerate}
  \item Use the actual batting averages from the 148 players with at least 400 at-bats:
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{pdata}\hlstd{(}\hlopt{~}\hlstd{BAvg,} \hlkwc{q} \hlstd{=} \hlnum{.300}\hlstd{,} \hlkwc{data} \hlstd{=} \hlkwd{filter}\hlstd{(mlb, yearID} \hlopt{==} \hlnum{1980}\hlstd{))}
\end{alltt}
\end{kframe}
\end{knitrout}

  \item \emph{Assume that batting average is distributed normally} and use the observed mean and standard deviation to specify the distribuion:
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{xpnorm}\hlstd{(}\hlnum{.300}\hlstd{,} \hlkwc{mean} \hlstd{=} \hlnum{.279}\hlstd{,} \hlkwc{sd} \hlstd{=} \hlnum{0.0276}\hlstd{)}
\hlkwd{pnorm}\hlstd{(}\hlnum{.300}\hlstd{,} \hlkwc{mean} \hlstd{=} \hlnum{.279}\hlstd{,} \hlkwc{sd} \hlstd{=} \hlnum{0.0276}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

  \item Simulate the distribution using R's random number generating capabilities:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{sim} \hlkwb{<-} \hlkwd{data.frame}\hlstd{(}\hlkwc{BAvg} \hlstd{=} \hlkwd{rnorm}\hlstd{(}\hlnum{10000}\hlstd{,} \hlkwc{mean} \hlstd{=} \hlnum{.279}\hlstd{,} \hlkwc{sd} \hlstd{=} \hlnum{0.0276}\hlstd{))}
\hlkwd{pdata}\hlstd{(}\hlopt{~}\hlstd{BAvg,} \hlkwc{q} \hlstd{=} \hlnum{.300}\hlstd{,} \hlkwc{data} \hlstd{= sim)}
\end{alltt}
\end{kframe}
\end{knitrout}




\end{enumerate}

\paragraph{Visualizing Confidence Intervals}

Open the following URL in a web browser:

\begin{center}
  \url{http://shiny.calvin.edu/rpruim/CIs/}
\end{center}

\begin{itemize}
  \itemsep0.25in
  \item Experiment with changing the sample size. How does that change the coverage rate? How does it change the confidence intervals? 
%  \item Experiment with changing the number of samples. How does that change the coverage rate? 
  \item Experiment with changing the confidence level. Does increasing the confidence level make the intervals wider or narrower?
  \item Experiment with changing the population distribution from normal to something non-normal. How does that change the coverage rate? 
  \vspace{0.5in}
\end{itemize}

\paragraph{Twitter Users and News} A poll conducted in 2013 found that 52\% of U.S. adult Twitter users get at least some news on Twitter. The standard error for this estimate was 2.4\%, and a normal distribution may be used to model the sample proportion. 
\begin{enumerate}
  \itemsep0.5in
  \item Draw a picture of the sampling distribution of the proportion of U.S. adult Twitters users who get at least some news on Twitter. 
  \item Construct a 99\% confidence interval for the fraction of U.S. adult Twitter users who get some news on Twitter.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{qnorm}\hlstd{(}\hlnum{0.995}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 2.575829
\end{verbatim}
\end{kframe}
\end{knitrout}


  \item Interpret the confidence interval in context.
  \item Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.
  \begin{enumerate}
    \itemsep0.5in
    \item The data provide statistically significant evidence that more than half of U.S. adult Twitter users get some news through Twitter. Use a significance level of $\alpha = 0.01$.
    \item Since the standard error is 2.4\%, we can conclude that 97.6\% of all U.S. adult Twitter users were included in the study.
    \item If we want to reduce the standard error of the estimate, we should collect less data.
    \item If we construct a 90\% confidence interval for the percentage of U.S. adults Twitter users who get some news through Twitter, this confidence interval will be wider than a corresponding 99\% confidence interval.
    \item If we repeated this study 1,000 times and constructed a 99\% confidence interval for each study, then approximately 990 of those confidence intervals whould contain the true fraction of U.S. adult Twitter users who get at least some news on Twitter. 
    \item The margin of error in this poll is less than 3 percentage points.
  \end{enumerate}
\end{enumerate}


% \newpage
% 
% \subsection*{Instructor's Notes}
% 
% 
% \paragraph{Confidence Intervals}
% 
% \begin{itemize}
%   \item $p$ is the unknown true, fixed, population parameter
%   \item $\hat{p}$ is the known, fixed, sample statistic
%   \item $\hat{p}$ is subject to variability due to sampling $\Rightarrow$ it has a sampling distribution!
%   \item $SE_{\hat{p}}$ is the standard deviation of the sampling distribution of $\hat{p}$
%   \item General form for a $(1- \alpha)$ \% confidence interval:
%   \begin{align*}
%       \text{point estimate} &\pm \text{margin of error} \\
%       \text{point estimate} &\pm \left( \text{something depending on } \alpha \text{, shape of samp. dist.}\right) \cdot \left( \text{standard error} \right) \\
%       \hat{p} &\pm z_{\alpha/2}^* \cdot SE_{\hat{p}}
%   \end{align*}
%   \item Question: Does CI contain $p$?
%   \item Answer: Yes or No, but we will never know!
%   \item Compromise: can we make a statement about \st{probability} \st{how likely} how \href{http://en.wikipedia.org/wiki/Confidence_interval#Misunderstandings}{\emph{confident}} we are that the CI contains $p$?
%    \item Interpretation: a level $C$ \emph{confidence interval} for the population mean will contain the true population mean $C\%$ of the time in repeated sampling.
%   \item Connection between significance tests and confidence intervals:
%   \begin{center}
%     95\% CI for a population parameter does not include the null value\\
%     $\Updownarrow$\\
%     $p$-value associated with the test statistic is less than $0.05$
%   \end{center}
% 
%   \item Key Notions that prevent misinterpretations:
%   \begin{itemize}
%     \item $p$ is unknown, and its value \textbf{does not change}.
%     \item The \textbf{one} sample proportion ($\hat{p}$) does not change either, and the confidence interval that you construct from it either will or will not contain the true mean (no chance involved).
%     \item Your CI is for the \emph{true proportion}, it doesn't say anything about individual observations.
%   \end{itemize}
%   \item Always report \st{$p$-values and} a confidence interval
%   \item Caveat: The margin of error represents a lower bound on the true uncertainty, for a variety of practical reasons.
% \end{itemize}
% 
% 
% Let $X$ be a random variable, and suppose that the true population $\mu_X$ is unknown. As statisticians, we want to estimate it. Our process is to draw a sample of $n$ observations of $X$, and take the average value of the items in that sample. This is the sample mean $\bar{x}$. Assume for now that we happen to know $\sigma_X$, the true population standard deviation (even though this is not realistic). What can we say about $\mu_X$? Our intuition tells us that $\bar{x}$ is close to $\mu_X$, but how close? How can we be sure?
% 
% \begin{itemize}
%  \item $SE_{\bar{X}}$ is the standard deviation of the sampling distribution of the mean. Thus far, we have obtained the sampling distributions via simulation, so we can compute the $SE_{\bar{X}}$ as the standard deviation of that simulated distribtion. Thus, $SE_{\bar{X}} = \sigma_{\bar{X}} \neq \sigma_X$.
%  \item Observation: $\mu_X$ lies within 2 SE's of $\bar{x} \iff \bar{x}$ lies within w SE's of $\mu_X$.
%  \item We know from the Law of Large Numbers that $\bar{x}$ converges to $\mu_X$ as $n$ increases
%  \item We know from the CLT that the distribution of $\bar{x}$ is approximately Normal
% $(\mu_X, \sigma_X / \sqrt{n})$.
%  \item Idea: We can use this information to make a precise statement about how likely it is that a specified range contains the true, unknown value of $\mu_X$, which is fixed.
%  \item Thus, a $1-\alpha$\% confidence interval for a population mean is:
%  $$
%    \left[ \bar{x} - z_{\alpha/2}^* \cdot SE_{\bar{X}}, \bar{x} + z_{\alpha/2}^* \cdot SE_{\bar{X}} \right]
%  $$
%  \item Important: In reality, you typically will have \textbf{one} sample, and the confidence interval that you construct from it either will or will not contain the true mean (no chance involved). Unfortunately, you'll never learn the true value of the population mean, so you won't ever know definitively. Thus, the goal is to make a probabilistic statement reflecting the likelihood that your confidence interval contains the true mean.
%  \item The sample mean $\bar{x}$ is an unbiased \emph{estimate} of the true population mean $\mu_X$.
%  \item We'll use our knowledge of the sampling distribution of $\bar{x}$ to construct a \emph{margin of error} around this estimate.
% 
% \end{itemize}




\end{document}
