---
title: "Sampling Distributions"
author: "Your Name"
date: "10/14/2014"
---


```{r, message=FALSE}
require(oilabs)
require(mosaic)
data(ames)
# rename two variables to make life easier
ames <- ames %>%
  rename(area = Gr.Liv.Area) %>%
  rename(price = SalePrice)
# change the number to something you like
set.rseed(42)
```

So far, we have only focused on estimating the mean living area in homes in Ames.  Now you'll try to estimate the mean home price.

##### Question 1

Take a sample of size 15 from the population and calculate the mean `price`
of the homes in this sample. Using this sample, what is your best point estimate
of the population mean of prices of homes?
    
##### Question 2

Since you have access to the population, simulate the sampling 
distribution for $\bar{x}_{price}$ by taking 2000 samples from the 
population of size 15 and computing 2000 sample means. Store these means 
in a vector called `sample_means15`. Plot the data, then describe the 
shape of this sampling distribution. Based on this sampling distribution, 
what would you guess the mean home price of the population to be? Finally, 
calculate and report the population mean.

##### Question 3

Change your sample size from 15 to 150, then compute the sampling 
distribution using the same method as above, and store these means in a 
new vector called `sample_means150`. Describe the shape of this sampling 
distribution, and compare it to the sampling distribution for a sample 
size of 15. Based on this sampling distribution, what would you guess to 
be the mean sale price of homes in Ames?
    
##### Question 4

Of the sampling distributions from 2 and 3, which has a smaller spread?  If
we're concerned with making estimates that are more often close to the 
true value, would we prefer a sampling distribution with a large or small spread?
