---
title: "Probability"
author: "Your Name"
date: "11/4/2015"
---

```{r load-data, message=FALSE, warning=FALSE}
library(mosaic)
library(oilabs)
set.rseed(100) # put in your favorite number in place of 100
```

## Comparing Kobe Bryant to the Independent Shooter. 

Using `calc_streak`, compute the streak lengths of `sim_basket`.

## Question 1
Describe the distribution of streak lengths. What is the typical streak length for this simulated independent shooter with a 45% shooting percentage? How long is the player's longest streak of baskets in 133 shots?

## Question 2
If you were to run the simulation of the independent shooter a second time, how would you expect its streak distribution to compare to the distribution from the question above? Exactly the same? Somewhat similar? Totally different? Explain your reasoning.
    
## Question 3

How does Kobe Bryant's distribution of streak lengths compare to the distribution of streak lengths for the simulated shooter? Using this comparison, do you have evidence that the hot hand model fits Kobe's  shooting patterns? Explain.