---
title: "Multiple Regression"
author: "Your Name"
date: "12/8/2015"
---

```{r, message=FALSE, warning=FALSE}
require(oilabs)
require(mosaic)
m_full <- lm(score ~ rank + ethnicity + gender + language + age + cls_perc_eval 
             + cls_students + cls_level + cls_profs + cls_credits + bty_avg 
             + pic_outfit + pic_color, data = evals)
summary(m_full)
```

##### Question 1 (Exercise 13)

Interpret the coefficient associated with the ethnicity variable.

##### Question 2 (Exercise 14)

Drop the variable with the highest p-value and re-fit the model. Did the coefficients and significance of the other explanatory variables change? (One of the things that makes multiple regression interesting is that coefficient estimates depend on the other variables that are included in the model.) If not, what does this say about whether or not the dropped variable was collinear with the other explanatory variables?

##### Question 3 (Exercise 15)

Using backward-selection and p-value as the selection criterion, determine the best model. You do not need to show all steps in your answer, just the output for the final model. Also, write out the linear model for predicting score based on the final model you settle on.

##### Question 4 (Exercise 16)

Verify that the conditions for this model are reasonable using diagnostic plots.

##### Question 5 (Exercise 17)

The original paper describes how these data were gathered by taking a sample of professors from the University of Texas at Austin and including all courses that they have taught. Considering that each row represents a course, could this new information have an impact on any of the conditions of linear regression?

##### Question 6 (Exercise 18)

Based on your final model, describe the characteristics of a professor and course at University of Texas at Austin that would be associated with a high evaluation score.

##### Question 7 (Exercise 19)

Would you be comfortable generalizing your conclusions to apply to professors generally (at any university)? Why or why not?