---
title: "Introduction to Data"
author: "Your Name"
date: "09/23/2015"
---

```{r, message=FALSE}
require(oilabs)
require(mosaic)
```


##### Question 1

Make a scatterplot of weight versus desired weight. Describe the relationship between these two variables.

##### Question 2

Let's consider a new variable: the difference between desired weight (`wtdesire`) and current weight (`weight`). Create this new variable by subtracting the two columns in the data frame and assigning them to a new object called `wdiff`.

##### Question 3

What type of data is `wdiff`? If an observation `wdiff` is 0, what does this mean about the person's weight and desired weight. What if `wdiff` is positive or negative?

##### Question 4

Describe the distribution of `wdiff` in terms of its center, shape, and spread, including any plots you use. What does this tell us about how people feel about their current weight?

##### Question 5

Using numerical summaries and a side-by-side box plot, determine if men tend to view their weight differently than women.

##### Question 6

Now it's time to get creative. Find the mean and standard deviation of `weight` and determine what proportion of the weights are within one standard deviation of the mean.
